version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
#    depends_on:
#      - db
#  db:
#    image: postgres:10
#    restart: always
#    ports:
#      - "6432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER: root
#      - POSTGRES_PASSWORD: 1111
#      - POSTGRES_DB: db_test
#volumes:
#  db-data::
